# Generated by Django 4.0.3 on 2022-04-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vehicles',
            new_name='vehicls',
        ),
    ]
